services:
  # user
  edot-user-rest:
    image: fenkygouw/edot-user:latest
    command: ["/app/edot-user-be", "rest"]
    ports:
      - "9100:9000"
    expose:
      - 9100
    depends_on:
      edot-user-postgres:
        condition: service_healthy
    networks:
      edot-network:
        aliases:
          - edot-user-rest
    environment:
      DATABASE_URL: "postgres://user:password@edot-user-postgres:5432/edot_user_db?sslmode=disable"
      JWT_SECRET: "u8EqBH/goITDyY5acas99221Ot/m+wbiGa5DpiiW878="
  edot-user-postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: edot_user_db
    ports:
      - 5532:5432
    expose:
      - 5532
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - edot-user-db:/var/lib/postgresql/data
    networks:
      edot-network:
        aliases:
          - edot-user-postgres
  edot-user-migrate:
    image: migrate/migrate
    depends_on:
      edot-user-postgres:
        condition: service_healthy
    networks:
      - edot-network
    volumes:
      - ./user/migration:/migration
    command: ["-path", "/migration", "-database",  "postgres://user:password@edot-user-postgres:5432/edot_user_db?sslmode=disable", "up"]
  # shop
  edot-shop-rest:
    image: fenkygouw/edot-shop:latest
    command: ["/app/edot-shop-be", "rest"]
    ports:
      - "9200:9000"
    expose:
      - 9200
    depends_on:
      edot-shop-postgres:
        condition: service_healthy
    networks:
      edot-network:
        aliases:
          - edot-shop-rest
    environment:
      DATABASE_URL: "postgres://user:password@edot-shop-postgres:5432/edot_shop_db?sslmode=disable"
      USER_REST_SERVICE_ADDRESS: "http://edot-user-rest:9000"
  edot-shop-postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: edot_shop_db
    ports:
      - 5632:5432
    expose:
      - 5632
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - edot-shop-db:/var/lib/postgresql/data
    networks:
      edot-network:
        aliases:
          - edot-shop-postgres
  edot-shop-migrate:
    image: migrate/migrate
    depends_on:
      edot-shop-postgres:
        condition: service_healthy
    networks:
      - edot-network
    volumes:
      - ./shop/migration:/migration
    command: ["-path", "/migration", "-database",  "postgres://user:password@edot-shop-postgres:5432/edot_shop_db?sslmode=disable", "up"]
  # product
  edot-product-rest:
    image: fenkygouw/edot-product:latest
    command: ["/app/edot-product-be", "rest"]
    ports:
      - "9300:9000"
    expose:
      - 9300
    depends_on:
      edot-product-postgres:
        condition: service_healthy
    networks:
      edot-network:
        aliases:
          - edot-product-rest
    environment:
      DATABASE_URL: "postgres://user:password@edot-product-postgres:5432/edot_product_db?sslmode=disable"
      USER_REST_SERVICE_ADDRESS: "http://edot-user-rest:9000"
      SHOP_REST_SERVICE_ADDRESS: "http://edot-shop-rest:9000"
      WAREHOUSE_REST_SERVICE_ADDRESS: "http://edot-warehouse-rest:9000"
  edot-product-postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: edot_product_db
    ports:
      - 5732:5432
    expose:
      - 5732
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - edot-product-db:/var/lib/postgresql/data
    networks:
      edot-network:
        aliases:
          - edot-product-postgres
  edot-product-migrate:
    image: migrate/migrate
    depends_on:
      edot-product-postgres:
        condition: service_healthy
    networks:
      - edot-network
    volumes:
      - ./product/migration:/migration
    command: ["-path", "/migration", "-database",  "postgres://user:password@edot-product-postgres:5432/edot_product_db?sslmode=disable", "up"]
  # warehouse
  edot-warehouse-rest:
    image: fenkygouw/edot-warehouse:latest
    command: ["/app/edot-warehouse-be", "rest"]
    ports:
      - "9400:9000"
    expose:
      - 9400
    depends_on:
      edot-warehouse-postgres:
        condition: service_healthy
    networks:
      edot-network:
        aliases:
          - edot-warehouse-rest
    environment:
      DATABASE_URL: "postgres://user:password@edot-warehouse-postgres:5432/edot_warehouse_db?sslmode=disable"
      USER_REST_SERVICE_ADDRESS: "http://edot-user-rest:9000"
      SHOP_REST_SERVICE_ADDRESS: "http://edot-shop-rest:9000"
      PRODUCT_REST_SERVICE_ADDRESS: "http://edot-product-rest:9000"
      REST_API_KEY_EXT_ORDER: "b8f3e7a9c2d645fba01e8c7d4f92ab3d"
  edot-warehouse-postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: edot_warehouse_db
    ports:
      - 5832:5432
    expose:
      - 5832
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - edot-warehouse-db:/var/lib/postgresql/data
    networks:
      edot-network:
        aliases:
          - edot-warehouse-postgres
  edot-warehouse-migrate:
    image: migrate/migrate
    depends_on:
      edot-warehouse-postgres:
        condition: service_healthy
    networks:
      - edot-network
    volumes:
      - ./warehouse/migration:/migration
    command: ["-path", "/migration", "-database",  "postgres://user:password@edot-warehouse-postgres:5432/edot_warehouse_db?sslmode=disable", "up"]
  # order
  edot-order-rest:
    image: fenkygouw/edot-order:latest
    command: ["/app/edot-order-be", "rest"]
    ports:
      - "9500:9000"
    expose:
      - 9500
    depends_on:
      edot-order-postgres:
        condition: service_healthy
    networks:
      edot-network:
        aliases:
          - edot-order-rest
    environment:
      DATABASE_URL: "postgres://user:password@edot-order-postgres:5432/edot_order_db?sslmode=disable"
      USER_REST_SERVICE_ADDRESS: "http://edot-user-rest:9000"
      SHOP_REST_SERVICE_ADDRESS: "http://edot-shop-rest:9000"
      PRODUCT_REST_SERVICE_ADDRESS: "http://edot-product-rest:9000"
      WAREHOUSE_REST_SERVICE_ADDRESS: "http://edot-warehouse-rest:9000"
      WAREHOUSE_REST_SERVICE_API_KEY: "b8f3e7a9c2d645fba01e8c7d4f92ab3d"
  edot-order-cron:
    image: fenkygouw/edot-order:latest
    command: ["/app/edot-order-be", "cron"]
    depends_on:
      edot-order-postgres:
        condition: service_healthy
    networks:
      edot-network:
        aliases:
          - edot-order-cron
    environment:
      DATABASE_URL: "postgres://user:password@edot-order-postgres:5432/edot_order_db?sslmode=disable"
      USER_REST_SERVICE_ADDRESS: "http://edot-user-rest:9000"
      SHOP_REST_SERVICE_ADDRESS: "http://edot-shop-rest:9000"
      PRODUCT_REST_SERVICE_ADDRESS: "http://edot-product-rest:9000"
      WAREHOUSE_REST_SERVICE_ADDRESS: "http://edot-warehouse-rest:9000"
      WAREHOUSE_REST_SERVICE_API_KEY: "b8f3e7a9c2d645fba01e8c7d4f92ab3d"
  edot-order-postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: edot_order_db
    ports:
      - 5932:5432
    expose:
      - 5932
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - edot-order-db:/var/lib/postgresql/data
    networks:
      edot-network:
        aliases:
          - edot-order-postgres
  edot-order-migrate:
    image: migrate/migrate
    depends_on:
      edot-order-postgres:
        condition: service_healthy
    networks:
      - edot-network
    volumes:
      - ./order/migration:/migration
    command: ["-path", "/migration", "-database",  "postgres://user:password@edot-order-postgres:5432/edot_order_db?sslmode=disable", "up"]
volumes:
  edot-user-db:
    driver: local
  edot-shop-db:
    driver: local
  edot-product-db:
    driver: local
  edot-warehouse-db:
    driver: local
  edot-order-db:
    driver: local
networks:
  edot-network:
    external: true
