apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: edot-product-postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: edot-product-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edot-product-postgres
  template:
    metadata:
      labels:
        app: edot-product-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: edot-product-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: edot-product-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              value: "edot_product_db"
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: edot-product-postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: edot-product-postgres
spec:
  selector:
    app: edot-product-postgres
  ports:
    - protocol: TCP
      port: 5732
      targetPort: 5432
  type: LoadBalancer
