services:
  edot-shop-rest:
    build: 
      context: .
      dockerfile: Dockerfile
    image: edot-shop:latest
    command: ["/app/edot-shop-be", "rest"]
    ports:
      - "9200:9000"
    expose:
      - 9200
    depends_on:
      edot-shop-postgres:
        condition: service_healthy
    networks:
      edot-network:
        aliases:
          - edot-shop-rest
    environment:
      DATABASE_URL: "postgres://user:password@edot-shop-postgres:5432/edot_shop_db?sslmode=disable"
      USER_REST_SERVICE_ADDRESS: "http://edot-user-rest:9000"
  edot-shop-postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: edot_shop_db
    ports:
      - 5632:5432
    expose:
      - 5632
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - edot-shop-db:/var/lib/postgresql/data
    networks:
      edot-network:
        aliases:
          - edot-shop-postgres
  edot-shop-migrate:
    image: migrate/migrate
    depends_on:
      edot-shop-postgres:
        condition: service_healthy
    networks:
      - edot-network
    volumes:
      - ./migration:/migration
    command: ["-path", "/migration", "-database",  "postgres://user:password@edot-shop-postgres:5432/edot_shop_db?sslmode=disable", "up"]
volumes:
  edot-shop-db:
    driver: local
networks:
  edot-network:
    external: true
