apiVersion: v1
kind: Secret
metadata:
  name: edot-shop-secret
type: Opaque
data:
  POSTGRES_USER: dXNlcg==
  POSTGRES_PASSWORD: cGFzc3dvcmQ=
  DATABASE_URL: cG9zdGdyZXM6Ly91c2VyOnBhc3N3b3JkQGVkb3Qtc2hvcC1wb3N0Z3Jlczo1NjMyL2Vkb3Rfc2hvcF9kYj9zc2xtb2RlPWRpc2FibGU=
