package error

import "errors"

var (
	ErrMissingAuthToken                = errors.New("missing auth token")
	ErrInvalidAuthTokenFormat          = errors.New("invalid auth token format")
	ErrGetUserProfile                  = errors.New("error occurred when getting user profile")
	ErrNoJWT                           = errors.New("no jwt")
	ErrNoUserId                        = errors.New("no user id")
	ErrInvalidUserId                   = errors.New("invalid user id")
	ErrMissingApiKey                   = errors.New("missing api key")
	ErrInvalidApiKey                   = errors.New("invalid api key")
	ErrMissingRequestBody              = errors.New("Missing request body.")
	ErrInvalidRequestBody              = errors.New("Invalid request body.")
	ErrInvalidName                     = errors.New("invalid name")
	ErrInvalidStatus                   = errors.New("invalid status")
	ErrInvalidUpdateRequest            = errors.New("invalid update request")
	ErrInvalidWarehouseId              = errors.New("invalid warehouse id")
	ErrInvalidProductId                = errors.New("invalid product id")
	ErrMinOneProductIdQueryParam       = errors.New("minimum one product id in query param")
	ErrMaxWarehousePerShop             = errors.New("reached max warehouse allowed per shop")
	ErrWarehouseNotFound               = errors.New("warehouse not found")
	ErrNotWarehouseOwner               = errors.New("not warehouse owner")
	ErrInvalidStock                    = errors.New("invalid stock")
	ErrInvalidStockTransfer            = errors.New("invalid stock transfer")
	ErrNotProductOwner                 = errors.New("not product owner")
	ErrInvalidStockTransferDestination = errors.New("invalid stock transfer destination")
	ErrStockLocked                     = errors.New("stock is locked")
	ErrInsufficientStock               = errors.New("insufficient stock")
	ErrWarehouseInactive               = errors.New("warehouse is inactive")
	ErrInvalidQuantityDeduction        = errors.New("invalid quantity for deduction")

	// system error
	ErrDatabaseTransaction = errors.New("database transaction error")
	ErrGetMyShop           = errors.New("error occurred when getting my shop")
	ErrGetProductById      = errors.New("error occurred when getting product by id")
	ErrInsertWarehouse     = errors.New("error occurred when inserting warehouse")
	ErrUpdateWarehouse     = errors.New("error occurred when updating warehouse")
	ErrGetWarehouses       = errors.New("error occurred when getting warehouses")
	ErrGetStocks           = errors.New("error occurred when getting stocks")
	ErrUpsertStock         = errors.New("error occurred when upserting stock")
	ErrDeductStock         = errors.New("error occurred when deducting stock")
)
