apiVersion: v1
kind: Secret
metadata:
  name: edot-user-secret
type: Opaque
data:
  POSTGRES_USER: dXNlcg==
  POSTGRES_PASSWORD: cGFzc3dvcmQ=
  DATABASE_URL: cG9zdGdyZXM6Ly91c2VyOnBhc3N3b3JkQGVkb3QtdXNlci1wb3N0Z3Jlczo1NTMyL2Vkb3RfdXNlcl9kYj9zc2xtb2RlPWRpc2FibGU=
  JWT_SECRET: dThFcUJIL2dvSVREeVk1YWNhczk5MjIxT3QvbSt3YmlHYTVEcGlpVzg3OD0=
