apiVersion: apps/v1
kind: Deployment
metadata:
  name: edot-product-rest
  labels:
    app: edot-product-rest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edot-product-rest
  template:
    metadata:
      labels:
        app: edot-product-rest
    spec:
      containers:
        - name: edot-product
          image: fenkygouw/edot-product:latest
          ports:
            - containerPort: 9000
          env:
            - name: DATABASE_URL
              value: "postgres://user:password@edot-product-postgres:5732/edot_product_db?sslmode=disable"
            - name: USER_REST_SERVICE_ADDRESS
              value: "http://edot-user-rest:9100"
            - name: SHOP_REST_SERVICE_ADDRESS
              value: "http://edot-shop-rest:9200"
            - name: WAREHOUSE_REST_SERVICE_ADDRESS
              value: "http://edot-warehouse-rest:9400"
---
apiVersion: v1
kind: Service
metadata:
  name: edot-product-rest
spec:
  selector:
    app: edot-product-rest
  ports:
    - protocol: TCP
      port: 9300
      targetPort: 9000
      nodePort: 30300
  type: NodePort
