apiVersion: apps/v1
kind: Deployment
metadata:
  name: edot-order-rest
  labels:
    app: edot-order-rest
spec:
  replicas: 3
  selector:
    matchLabels:
      app: edot-order-rest
  template:
    metadata:
      labels:
        app: edot-order-rest
    spec:
      containers:
        - name: edot-order
          image: fenkygouw/edot-order:latest
          ports:
            - containerPort: 9000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: edot-order-secret
                  key: DATABASE_URL
            - name: USER_REST_SERVICE_ADDRESS
              value: "http://edot-user-rest:9100"
            - name: SHOP_REST_SERVICE_ADDRESS
              value: "http://edot-shop-rest:9200"
            - name: PRODUCT_REST_SERVICE_ADDRESS
              value: "http://edot-product-rest:9300"
            - name: WAREHOUSE_REST_SERVICE_ADDRESS
              value: "http://edot-warehouse-rest:9400"
            - name: WAREHOUSE_REST_SERVICE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: edot-order-secret
                  key: WAREHOUSE_REST_SERVICE_API_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: edot-order-rest
spec:
  selector:
    app: edot-order-rest
  ports:
    - protocol: TCP
      port: 9500
      targetPort: 9000
  type: LoadBalancer
