services:
  edot-product-rest:
    build: 
      context: .
      dockerfile: Dockerfile
    image: edot-product:latest
    command: ["/app/edot-product-be", "rest"]
    ports:
      - "9300:9000"
    expose:
      - 9300
    depends_on:
      edot-product-postgres:
        condition: service_healthy
    networks:
      edot-network:
        aliases:
          - edot-product-rest
    environment:
      DATABASE_URL: "postgres://user:password@edot-product-postgres:5432/edot_product_db?sslmode=disable"
      USER_REST_SERVICE_ADDRESS: "http://edot-user-rest:9000"
      SHOP_REST_SERVICE_ADDRESS: "http://edot-shop-rest:9000"
      WAREHOUSE_REST_SERVICE_ADDRESS: "http://edot-warehouse-rest:9000"
  edot-product-postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: edot_product_db
    ports:
      - 5732:5432
    expose:
      - 5732
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - edot-product-db:/var/lib/postgresql/data
    networks:
      edot-network:
        aliases:
          - edot-product-postgres
  edot-product-migrate:
    image: migrate/migrate
    depends_on:
      edot-product-postgres:
        condition: service_healthy
    networks:
      - edot-network
    volumes:
      - ./migration:/migration
    command: ["-path", "/migration", "-database",  "postgres://user:password@edot-product-postgres:5432/edot_product_db?sslmode=disable", "up"]
volumes:
  edot-product-db:
    driver: local
networks:
  edot-network:
    external: true
