services:
  edot-user-rest:
    build: 
      context: .
      dockerfile: Dockerfile
    image: edot-user:latest
    command: ["/app/edot-user-be", "rest"]
    ports:
      - "9100:9000"
    expose:
      - 9100
    depends_on:
      edot-user-postgres:
        condition: service_healthy
    networks:
      edot-network:
        aliases:
          - edot-user-rest
    environment:
      DATABASE_URL: "postgres://user:password@edot-user-postgres:5432/edot_user_db?sslmode=disable"
      JWT_SECRET: "u8EqBH/goITDyY5acas99221Ot/m+wbiGa5DpiiW878="
  edot-user-postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: edot_user_db
    ports:
      - 5532:5432
    expose:
      - 5532
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - edot-user-db:/var/lib/postgresql/data
    networks:
      edot-network:
        aliases:
          - edot-user-postgres
  edot-user-migrate:
    image: migrate/migrate
    depends_on:
      edot-user-postgres:
        condition: service_healthy
    networks:
      - edot-network
    volumes:
      - ./migration:/migration
    command: ["-path", "/migration", "-database",  "postgres://user:password@edot-user-postgres:5432/edot_user_db?sslmode=disable", "up"]
volumes:
  edot-user-db:
    driver: local
networks:
  edot-network:
    external: true
