services:
  app:
    build: .
    ports:
      - "9100:9000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      edot-network:
        aliases:
          - edot-user-app
    environment:
      DATABASE_URL: "postgres://user:password@edot-user-postgres:5432/edot_user_db?sslmode=disable"
      JWT_SECRET: "u8EqBH/goITDyY5acas99221Ot/m+wbiGa5DpiiW878="
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: edot_user_db
    ports:
      - 5532:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 3
    expose:
      - 5532
    volumes:
      - edot-user-db:/var/lib/postgresql/data
    networks:
      edot-network:
        aliases:
          - edot-user-postgres
  migrate:
    image: migrate/migrate
    depends_on:
      db:
        condition: service_healthy
    networks:
      - edot-network
    volumes:
      - ./migration:/migration
    command: ["-path", "/migration", "-database",  "postgres://user:password@edot-user-postgres:5432/edot_user_db?sslmode=disable", "up"]
volumes:
  edot-user-db:
    driver: local
networks:
  edot-network:
    external: true
